from rclpy.duration import Duration
from rclpy.time import Time

from geometry_msgs.msg import TransformStamped

class TransformException(Exception): ...
class ConnectivityException(TransformException): ...
class ExtrapolationException(TransformException): ...
class InvalidArgumentException(TransformException): ...
class LookupException(TransformException): ...
class TimeoutException(TransformException): ...

class BufferCore:
    def __init__(self, cache_time: Duration | None = None) -> None: ...
    def set_transform(self, transform: TransformStamped, authority: str) -> None: ...
    def set_transform_static(self, transform: TransformStamped, authority: str) -> None: ...
    def lookup_transform_core(self, target_frame: str, source_frame: str, time: Time) -> TransformStamped: ...
    def lookup_transform_full_core(
        self,
        target_frame: str,
        target_time: Time,
        source_frame: str,
        source_time: Time,
        fixed_frame: str,
    ) -> TransformStamped: ...
    def can_transform_core(self, target_frame: str, source_frame: str, time: Time) -> tuple[bool, str]: ...
    def can_transform_full_core(
        self,
        target_frame: str,
        target_time: Time,
        source_frame: str,
        source_time: Time,
        fixed_frame: str,
    ) -> tuple[bool, str]: ...
    def all_frames_as_yaml(self) -> str: ...
    def all_frames_as_string(self) -> str: ...
    def get_latest_common_time(self, target_frame: str, source_frame: str) -> Time: ...
    def clear(self) -> None: ...
